/**
 * Google Workspace Integration Service for DevPulse
 * Connects Google Drive, Google Docs, Google Tasks, Google Calendar, and Gmail
 */

const OAUTH_CLIENT_ID = '302460196835-u2th576dlo1ieflkn9ciag54gloj5vf9.apps.googleusercontent.com';

const SCOPES = [
  'https://www.googleapis.com/auth/drive.file',
  'https://www.googleapis.com/auth/documents',
  'https://www.googleapis.com/auth/tasks',
  'https://www.googleapis.com/auth/calendar.events',
  'https://www.googleapis.com/auth/gmail.compose',
].join(' ');

let currentAccessToken: string | null = null;

// Initialize or Request Google Access Token via Google Identity Services
export async function requestGoogleAccessToken(): Promise<string> {
  if (currentAccessToken) {
    return currentAccessToken;
  }

  return new Promise((resolve, reject) => {
    // Check if google scripts are available on window
    const gWindow = window as any;
    if (gWindow.google?.accounts?.oauth2) {
      try {
        const client = gWindow.google.accounts.oauth2.initTokenClient({
          client_id: OAUTH_CLIENT_ID,
          scope: SCOPES,
          callback: (response: any) => {
            if (response.error) {
              reject(new Error(response.error_description || response.error));
            } else {
              currentAccessToken = response.access_token;
              sessionStorage.setItem('devpulse_g_token', response.access_token);
              resolve(response.access_token);
            }
          },
        });
        client.requestAccessToken({ prompt: 'consent' });
      } catch (err) {
        reject(err);
      }
    } else {
      // Fallback: Check stored session token
      const stored = sessionStorage.getItem('devpulse_g_token');
      if (stored) {
        currentAccessToken = stored;
        resolve(stored);
      } else {
        // Mock-safe token for preview environments or prompt user
        reject(new Error('Google Identity Services is initializing. Please ensure popups are allowed.'));
      }
    }
  });
}

export function getStoredGoogleToken(): string | null {
  if (currentAccessToken) return currentAccessToken;
  return sessionStorage.getItem('devpulse_g_token');
}

export function hasGoogleWorkspaceAccess(): boolean {
  return !!getStoredGoogleToken();
}

export function clearGoogleToken(): void {
  currentAccessToken = null;
  sessionStorage.removeItem('devpulse_g_token');
}

export const clearStoredGoogleToken = clearGoogleToken;

// 1. Google Drive: Upload Analysis Report
export async function uploadReportToDrive(
  token: string,
  fileName: string,
  content: string | Blob,
  mimeType = 'text/markdown'
): Promise<{ id: string; name: string; webViewLink?: string }> {
  const metadata = {
    name: fileName,
    mimeType: mimeType,
    description: 'Generated by DevPulse Code Intelligence Platform',
  };

  const form = new FormData();
  form.append('metadata', new Blob([JSON.stringify(metadata)], { type: 'application/json' }));
  
  if (typeof content === 'string') {
    form.append('file', new Blob([content], { type: mimeType }));
  } else {
    form.append('file', content);
  }

  const response = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: form,
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google Drive upload failed (${response.status}): ${errorText}`);
  }

  return await response.json();
}

/**
 * GitHub Integration: Sync Report to GitHub Gist or Repository
 */
export async function syncReportToGitHubGist(
  fileName: string,
  content: string,
  description: string,
  githubToken?: string,
  isPublic = false
): Promise<{ id: string; htmlUrl: string; rawUrl?: string }> {
  const safeFileName = fileName.endsWith('.md') ? fileName : `${fileName}.md`;
  const payload = {
    description: description || `DevPulse Code Intelligence Report - ${new Date().toLocaleDateString()}`,
    public: isPublic,
    files: {
      [safeFileName]: {
        content: content,
      },
    },
  };

  const headers: Record<string, string> = {
    'Accept': 'application/vnd.github+json',
    'Content-Type': 'application/json',
  };

  if (githubToken && githubToken.trim().length > 0) {
    headers['Authorization'] = `Bearer ${githubToken.trim()}`;
  }

  const response = await fetch('https://api.github.com/gists', {
    method: 'POST',
    headers,
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`GitHub Gist sync failed (${response.status}): ${errText}`);
  }

  const data = await response.json();
  return {
    id: data.id,
    htmlUrl: data.html_url,
    rawUrl: data.files?.[safeFileName]?.raw_url,
  };
}

/**
 * GitHub Integration: Commit Report into a Repository (.github/reports/...)
 */
export async function syncReportToGitHubRepo(
  owner: string,
  repo: string,
  filePath: string,
  content: string,
  commitMessage: string,
  githubToken: string,
  branch = 'main'
): Promise<{ commitUrl: string; fileUrl: string }> {
  const encodedPath = encodeURIComponent(filePath).replace(/%2F/g, '/');
  const apiUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${encodedPath}`;

  const headers: Record<string, string> = {
    'Accept': 'application/vnd.github+json',
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${githubToken.trim()}`,
  };

  // Check if file already exists to get SHA for update
  let existingSha: string | undefined;
  try {
    const checkRes = await fetch(`${apiUrl}?ref=${branch}`, { headers });
    if (checkRes.ok) {
      const fileData = await checkRes.json();
      existingSha = fileData.sha;
    }
  } catch (e) {
    // File does not exist yet
  }

  // Base64 encode content (Unicode safe)
  const base64Content = btoa(unescape(encodeURIComponent(content)));

  const payload: any = {
    message: commitMessage || `docs(audit): add DevPulse code intelligence report [skip ci]`,
    content: base64Content,
    branch,
  };

  if (existingSha) {
    payload.sha = existingSha;
  }

  const putRes = await fetch(apiUrl, {
    method: 'PUT',
    headers,
    body: JSON.stringify(payload),
  });

  if (!putRes.ok) {
    const errText = await putRes.text();
    throw new Error(`GitHub repository push failed (${putRes.status}): ${errText}`);
  }

  const result = await putRes.json();
  return {
    commitUrl: result.commit?.html_url || `https://github.com/${owner}/${repo}/commit/${result.commit?.sha}`,
    fileUrl: result.content?.html_url || `https://github.com/${owner}/${repo}/blob/${branch}/${filePath}`,
  };
}

// 2. Google Docs: Create Structured Document
export async function createGoogleDoc(
  token: string,
  title: string,
  bodyText: string
): Promise<{ documentId: string; title: string; url: string }> {
  // Step 1: Create blank doc
  const createRes = await fetch('https://docs.googleapis.com/v1/documents', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ title }),
  });

  if (!createRes.ok) {
    const err = await createRes.text();
    throw new Error(`Failed to create Google Doc: ${err}`);
  }

  const docData = await createRes.json();
  const documentId = docData.documentId;

  // Step 2: Insert the content text
  if (bodyText) {
    await fetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        requests: [
          {
            insertText: {
              location: { index: 1 },
              text: bodyText,
            },
          },
        ],
      }),
    });
  }

  return {
    documentId,
    title,
    url: `https://docs.google.com/document/d/${documentId}/edit`,
  };
}

// 3. Google Tasks: Sync Code Smells as Actionable Tasks
export async function createGoogleTasksForSmells(
  token: string,
  smells: Array<{ title: string; line: number; description: string; severity?: string }>,
  projectName = 'DevPulse Code Health'
): Promise<{ count: number; taskListTitle: string }> {
  // Get or use default task list '@default'
  let createdCount = 0;

  for (const smell of smells.slice(0, 8)) {
    const taskPayload = {
      title: `[${(smell.severity || 'WARN').toUpperCase()}] Line ${smell.line}: ${smell.title}`,
      notes: `${smell.description}\n\nGenerated by DevPulse Observatory for ${projectName}`,
      due: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    };

    const res = await fetch('https://tasks.googleapis.com/tasks/v1/lists/@default/tasks', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(taskPayload),
    });

    if (res.ok) {
      createdCount++;
    }
  }

  return { count: createdCount, taskListTitle: 'Default Task List' };
}

// 4. Google Calendar: Schedule Code Review
export async function scheduleCodeReviewEvent(
  token: string,
  summary: string,
  description: string,
  startTimeIso?: string
): Promise<{ id: string; htmlLink: string }> {
  const start = startTimeIso ? new Date(startTimeIso) : new Date(Date.now() + 24 * 60 * 60 * 1000);
  const end = new Date(start.getTime() + 45 * 60 * 1000); // 45 min review

  const eventPayload = {
    summary: `DevPulse Review: ${summary}`,
    description: `${description}\n\nAutomated DevPulse Code Intelligence Session`,
    start: { dateTime: start.toISOString() },
    end: { dateTime: end.toISOString() },
    conferenceData: {
      createRequest: {
        requestId: `meet_${Date.now()}`,
        conferenceSolutionKey: { type: 'hangoutsMeet' },
      },
    },
  };

  const res = await fetch(
    'https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(eventPayload),
    }
  );

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Google Calendar event creation failed: ${err}`);
  }

  return await res.json();
}

// 5. Gmail: Create Code Audit Draft
export async function createGmailAuditDraft(
  token: string,
  subject: string,
  bodyText: string
): Promise<{ id: string; messageId: string }> {
  const emailLines = [
    `Subject: ${subject}`,
    'MIME-Version: 1.0',
    'Content-Type: text/plain; charset=UTF-8',
    '',
    bodyText,
  ];

  const raw = btoa(unescape(encodeURIComponent(emailLines.join('\r\n'))))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');

  const res = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/drafts', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      message: { raw },
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Gmail draft creation failed: ${err}`);
  }

  const data = await res.json();
  return { id: data.id, messageId: data.message?.id || data.id };
}
