import { jsPDF } from 'jspdf';
import { AnalysisResult, CodeSmell, StructureNode } from '../types';

export type ReportTemplatePreset = 'executive' | 'technical' | 'security' | 'minimal' | 'custom';
export type ReportAccentColor = 'teal' | 'indigo' | 'amber' | 'rose' | 'slate';

export interface ReportTemplateConfig {
  templatePreset: ReportTemplatePreset;
  organizationName: string;
  reportTitle: string;
  authorName: string;
  confidentialityNote: string;
  customSummaryNote: string;
  headerTagline: string;
  footerDisclaimer: string;
  accentColor: ReportAccentColor;
  blocks: {
    showHeader: boolean;
    showExecutiveSummary: boolean;
    showMetrics: boolean;
    showSmells: boolean;
    showFunctions: boolean;
    showDependencies: boolean;
    showPulseMap: boolean;
    showAiGuidance: boolean;
    showCustomNotes: boolean;
    showFooter: boolean;
  };
}

export interface ExportOptions {
  includeMetrics: boolean;
  includeSmells: boolean;
  includePulseMap: boolean;
  includeFunctions: boolean;
  includeImports: boolean;
  includeAiSummary?: boolean;
  template?: ReportTemplateConfig;
}

export const DEFAULT_TEMPLATE_CONFIG: ReportTemplateConfig = {
  templatePreset: 'technical',
  organizationName: 'DevPulse Engineering Labs',
  reportTitle: 'Code Intelligence & Pulse Map Audit',
  authorName: 'DevPulse Automated Auditor',
  confidentialityNote: 'Internal Engineering Use Only',
  customSummaryNote: 'This report provides an automated static analysis, cognitive complexity map, and security assessment.',
  headerTagline: 'See the Code. Find the Pulse.',
  footerDisclaimer: 'Confidential & Proprietary — Generated by DevPulse Observability Platform',
  accentColor: 'teal',
  blocks: {
    showHeader: true,
    showExecutiveSummary: true,
    showMetrics: true,
    showSmells: true,
    showFunctions: true,
    showDependencies: true,
    showPulseMap: true,
    showAiGuidance: true,
    showCustomNotes: true,
    showFooter: true,
  },
};

export const TEMPLATE_PRESETS: Record<ReportTemplatePreset, Partial<ReportTemplateConfig>> = {
  executive: {
    templatePreset: 'executive',
    reportTitle: 'Executive Codebase Health & Risk Brief',
    headerTagline: 'High-Level Governance & Maintainability Scorecard',
    confidentialityNote: 'Executive Briefing — Confidential',
    customSummaryNote: 'Strategic evaluation of codebase maintainability, technical debt risks, and release readiness.',
    accentColor: 'indigo',
    blocks: {
      showHeader: true,
      showExecutiveSummary: true,
      showMetrics: true,
      showSmells: true,
      showFunctions: false,
      showDependencies: true,
      showPulseMap: false,
      showAiGuidance: true,
      showCustomNotes: true,
      showFooter: true,
    },
  },
  technical: {
    templatePreset: 'technical',
    reportTitle: 'Technical Architecture & Pulse Map Audit',
    headerTagline: 'Comprehensive Structural & Complexity Breakdown',
    confidentialityNote: 'Engineering Platform Documentation',
    customSummaryNote: 'In-depth code diagnostic analysis including cyclomatic complexity, topology graph, and line-level findings.',
    accentColor: 'teal',
    blocks: {
      showHeader: true,
      showExecutiveSummary: true,
      showMetrics: true,
      showSmells: true,
      showFunctions: true,
      showDependencies: true,
      showPulseMap: true,
      showAiGuidance: true,
      showCustomNotes: true,
      showFooter: true,
    },
  },
  security: {
    templatePreset: 'security',
    reportTitle: 'Application Security & Vulnerability Audit',
    headerTagline: 'Threat Surface, Hygiene & Anti-Pattern Detection',
    confidentialityNote: 'Restricted — Security & Compliance Review',
    customSummaryNote: 'Dedicated security audit highlighting detected vulnerabilities, dangerous imports, and remediation guidance.',
    accentColor: 'rose',
    blocks: {
      showHeader: true,
      showExecutiveSummary: true,
      showMetrics: false,
      showSmells: true,
      showFunctions: false,
      showDependencies: true,
      showPulseMap: false,
      showAiGuidance: true,
      showCustomNotes: true,
      showFooter: true,
    },
  },
  minimal: {
    templatePreset: 'minimal',
    reportTitle: 'Developer Quick-Check Report',
    headerTagline: 'Rapid Code Smell & Metrics Summary',
    confidentialityNote: 'Internal Pull Request Note',
    customSummaryNote: 'Condensed summary for code reviews and quick diagnostic passes.',
    accentColor: 'amber',
    blocks: {
      showHeader: true,
      showExecutiveSummary: true,
      showMetrics: true,
      showSmells: true,
      showFunctions: false,
      showDependencies: false,
      showPulseMap: false,
      showAiGuidance: false,
      showCustomNotes: false,
      showFooter: false,
    },
  },
  custom: {
    templatePreset: 'custom',
    reportTitle: 'Custom Code Intelligence Report',
    headerTagline: 'Customized Layout & Branding Configuration',
    confidentialityNote: 'Custom Auditing Record',
    customSummaryNote: '',
    accentColor: 'teal',
    blocks: {
      showHeader: true,
      showExecutiveSummary: true,
      showMetrics: true,
      showSmells: true,
      showFunctions: true,
      showDependencies: true,
      showPulseMap: true,
      showAiGuidance: true,
      showCustomNotes: true,
      showFooter: true,
    },
  },
};

const defaultOptions: ExportOptions = {
  includeMetrics: true,
  includeSmells: true,
  includePulseMap: true,
  includeFunctions: true,
  includeImports: true,
  includeAiSummary: true,
  template: DEFAULT_TEMPLATE_CONFIG,
};

/**
 * Generate formatted JSON report string for analysis & intelligence findings
 */
export function generateJSONReport(
  analysis: AnalysisResult,
  code: string,
  fileName: string,
  aiSummaryText?: string
): string {
  const exportPayload = {
    metadata: {
      tool: 'DevPulse Intelligence Engine',
      tagline: 'See the Code. Find the Pulse.',
      exportedAt: new Date().toISOString(),
      fileName: fileName || 'untitled',
      language: analysis.language,
      languageName: analysis.languageName,
      linesOfCode: analysis.metrics.loc,
    },
    executiveSummary: {
      healthScore: analysis.metrics.healthScore,
      healthLevel: analysis.summary.healthLevel,
      maintainabilityScore: analysis.metrics.maintainabilityScore,
      cyclomaticComplexity: analysis.metrics.cyclomaticComplexity,
      cognitiveComplexity: analysis.metrics.cognitiveComplexity,
      smellsCount: analysis.smells.length,
      criticalSmellsCount: analysis.summary.criticalCount,
      warningSmellsCount: analysis.summary.warningCount,
      infoSmellsCount: analysis.summary.infoCount,
    },
    metrics: {
      loc: analysis.metrics.loc,
      sloc: analysis.metrics.sloc,
      blankLines: analysis.metrics.blankLines,
      commentLines: analysis.metrics.commentLines,
      commentRatio: analysis.metrics.commentRatio,
      cyclomaticComplexity: analysis.metrics.cyclomaticComplexity,
      cognitiveComplexity: analysis.metrics.cognitiveComplexity,
      maxNestingDepth: analysis.metrics.maxNestingDepth,
      functionCount: analysis.metrics.functionCount,
      classCount: analysis.metrics.classCount,
      averageFunctionLength: analysis.metrics.averageFunctionLength,
      dependenciesCount: analysis.metrics.dependenciesCount,
      externalDependenciesCount: analysis.metrics.externalDependenciesCount,
      internalDependenciesCount: analysis.metrics.internalDependenciesCount,
      scoreBreakdown: analysis.metrics.scoreBreakdown,
    },
    codeSmells: analysis.smells.map((s) => ({
      id: s.id,
      title: s.title,
      severity: s.severity,
      category: s.category,
      line: s.line,
      endLine: s.endLine,
      problem: s.problem,
      explanation: s.explanation,
      recommendation: s.recommendation,
      codeSnippet: s.codeSnippet,
    })),
    functions: analysis.metrics.functions.map((f) => ({
      name: f.name,
      line: f.line,
      endLine: f.endLine,
      loc: f.loc,
      params: f.params,
      paramNames: f.paramNames,
      complexity: f.complexity,
      cognitiveComplexity: f.cognitiveComplexity,
      nesting: f.nesting,
      isAsync: f.isAsync,
      returnType: f.returnType,
    })),
    classes: analysis.metrics.classes.map((c) => ({
      name: c.name,
      line: c.line,
      endLine: c.endLine,
      loc: c.loc,
      methodsCount: c.methodsCount,
      propertiesCount: c.propertiesCount,
      inheritance: c.inheritance,
    })),
    imports: analysis.metrics.imports.map((i) => ({
      module: i.module,
      names: i.names,
      isExternal: i.isExternal,
      line: i.line,
      riskNote: i.riskNote,
    })),
    pulseMap: {
      nodeCount: analysis.pulseMap.nodes.length,
      linkCount: analysis.pulseMap.links.length,
      nodes: analysis.pulseMap.nodes.map((n) => ({
        id: n.id,
        label: n.label,
        type: n.type,
        line: n.line,
        group: n.group,
        metrics: n.metrics,
      })),
      links: analysis.pulseMap.links.map((l) => ({
        source: l.source,
        target: l.target,
        relationship: l.relationship,
      })),
    },
    aiInsights: aiSummaryText ? { summary: aiSummaryText } : undefined,
    rawSourceCode: code,
  };

  return JSON.stringify(exportPayload, null, 2);
}

/**
 * Export Analysis & Pulse Map data as a JSON file
 */
export function exportAnalysisAsJSON(
  analysis: AnalysisResult,
  code: string,
  fileName: string,
  aiSummaryText?: string
): void {
  const jsonString = generateJSONReport(analysis, code, fileName, aiSummaryText);
  const blob = new Blob([jsonString], { type: 'application/json;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  const safeName = (fileName || 'code_intelligence').replace(/\.[^/.]+$/, '');
  link.href = url;
  link.download = `devpulse-intelligence-${safeName}-${new Date().toISOString().slice(0, 10)}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Helper to get RGB color tuple from ReportAccentColor
 */
export function getAccentColorRGB(accent: ReportAccentColor = 'teal'): {
  primary: [number, number, number];
  subtleBg: [number, number, number];
  border: [number, number, number];
  text: [number, number, number];
} {
  switch (accent) {
    case 'indigo':
      return {
        primary: [79, 70, 229], // #4F46E5
        subtleBg: [245, 247, 255],
        border: [218, 224, 250],
        text: [49, 46, 129],
      };
    case 'amber':
      return {
        primary: [217, 119, 6], // #D97706
        subtleBg: [255, 251, 235],
        border: [253, 230, 138],
        text: [146, 64, 14],
      };
    case 'rose':
      return {
        primary: [225, 29, 72], // #E11D48
        subtleBg: [255, 241, 242],
        border: [254, 205, 211],
        text: [159, 18, 57],
      };
    case 'slate':
      return {
        primary: [71, 85, 105], // #475569
        subtleBg: [248, 250, 252],
        border: [226, 232, 240],
        text: [30, 41, 59],
      };
    case 'teal':
    default:
      return {
        primary: [13, 148, 136], // #0D9488
        subtleBg: [245, 248, 247],
        border: [204, 225, 221],
        text: [15, 118, 110],
      };
  }
}

/**
 * Generate a comprehensive Markdown report of analysis & intelligence findings with template branding
 */
export function generateMarkdownReport(
  analysis: AnalysisResult,
  code: string,
  fileName: string,
  options: ExportOptions = defaultOptions,
  aiSummaryText?: string
): string {
  const template = options.template || DEFAULT_TEMPLATE_CONFIG;
  const blocks = template.blocks;

  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const lines: string[] = [];

  // 1. Header & Branding Block
  if (blocks.showHeader) {
    lines.push(
      `# 🩺 ${template.reportTitle || 'DevPulse Intelligence Report'}`,
      `> **${template.organizationName || 'DevPulse Engineering Labs'}** — *"${template.headerTagline || 'See the Code. Find the Pulse.'}"*`,
      ``,
      `| Property | Value |`,
      `| :--- | :--- |`,
      `| **Target File** | \`${fileName || 'untitled'}\` |`,
      `| **Language** | ${analysis.languageName} (\`${analysis.language}\`) |`,
      `| **Lines of Code (LOC)** | ${analysis.metrics.loc} |`,
      `| **Auditor / Author** | ${template.authorName || 'DevPulse Automated Engine'} |`,
      `| **Classification** | \`${template.confidentialityNote || 'Internal Use Only'}\` |`,
      `| **Generated At** | ${dateStr} |`,
      `| **Health Score** | **${analysis.metrics.healthScore}/100** (${analysis.summary.healthLevel.toUpperCase()}) |`,
      ``,
      `---`,
      ``
    );
  }

  // Custom Summary / Notes Block
  if (blocks.showCustomNotes && template.customSummaryNote && template.customSummaryNote.trim().length > 0) {
    lines.push(
      `## 📋 Scope & Executive Notes`,
      ``,
      `> ${template.customSummaryNote.trim()}`,
      ``,
      `---`,
      ``
    );
  }

  // 2. Executive Scorecard Block
  if (blocks.showExecutiveSummary) {
    lines.push(
      `## 📊 Executive Scorecard`,
      ``,
      `- **Health Score:** ${analysis.metrics.healthScore}/100 (${analysis.summary.healthLevel.toUpperCase()})`,
      `- **Maintainability Index:** ${analysis.metrics.maintainabilityScore}/100`,
      `- **Cyclomatic Complexity:** ${analysis.metrics.cyclomaticComplexity}`,
      `- **Cognitive Complexity:** ${analysis.metrics.cognitiveComplexity}`,
      `- **Max Nesting Depth:** ${analysis.metrics.maxNestingDepth}`,
      `- **Active Code Smells:** ${analysis.smells.length} (Critical: ${analysis.summary.criticalCount}, Warning: ${analysis.summary.warningCount}, Info: ${analysis.summary.infoCount})`,
      ``
    );
  }

  // 3. Metrics Matrix Block
  if (blocks.showMetrics && options.includeMetrics) {
    lines.push(
      `## 📈 Code Metrics Breakdown`,
      ``,
      `| Metric | Count | Details |`,
      `| :--- | :--- | :--- |`,
      `| **Source Lines (SLOC)** | ${analysis.metrics.sloc} | Pure executable statements |`,
      `| **Comment Lines** | ${analysis.metrics.commentLines} | Ratio: ${Math.round(analysis.metrics.commentRatio * 100)}% |`,
      `| **Blank Lines** | ${analysis.metrics.blankLines} | Layout spacing |`,
      `| **Functions / Methods** | ${analysis.metrics.functionCount} | Avg length: ${analysis.metrics.averageFunctionLength} lines |`,
      `| **Classes** | ${analysis.metrics.classCount} | Object definitions |`,
      `| **Dependencies** | ${analysis.metrics.dependenciesCount} | External: ${analysis.metrics.externalDependenciesCount}, Internal: ${analysis.metrics.internalDependenciesCount} |`,
      ``
    );
  }

  // 4. Code Smells & Findings Block
  if (blocks.showSmells && options.includeSmells && analysis.smells.length > 0) {
    lines.push(
      `## ⚠️ Detected Code Smells & Findings (${analysis.smells.length})`,
      ``
    );

    analysis.smells.forEach((smell: CodeSmell, idx: number) => {
      const sevEmoji = smell.severity === 'critical' ? '🔴' : smell.severity === 'warning' ? '🟡' : '🔵';
      lines.push(
        `### ${idx + 1}. ${sevEmoji} [${smell.severity.toUpperCase()}] ${smell.title}`,
        `- **Location:** Line ${smell.line}${smell.endLine ? `–${smell.endLine}` : ''}`,
        `- **Category:** \`${smell.category}\``,
        `- **Problem:** ${smell.problem}`,
        `- **Explanation:** ${smell.explanation}`,
        `- **Recommended Fix:** ${smell.recommendation}`,
        ``
      );

      if (smell.codeSnippet) {
        lines.push(
          `\`\`\`${analysis.language}`,
          smell.codeSnippet.trim(),
          `\`\`\``,
          ``
        );
      }
    });
  }

  // 5. Function Map Block
  if (blocks.showFunctions && options.includeFunctions && analysis.metrics.functions.length > 0) {
    lines.push(
      `## 🧩 Function & Method Complexity Map`,
      ``,
      `| Function | Line | LOC | Cyclomatic | Cognitive | Nesting | Async |`,
      `| :--- | :--- | :--- | :--- | :--- | :--- | :--- |`
    );

    analysis.metrics.functions.forEach((fn) => {
      lines.push(
        `| \`${fn.name}()\` | ${fn.line} | ${fn.loc} | ${fn.complexity} | ${fn.cognitiveComplexity} | ${fn.nesting} | ${fn.isAsync ? 'Yes' : 'No'} |`
      );
    });
    lines.push(``);
  }

  // 6. Dependencies Block
  if (blocks.showDependencies && options.includeImports && analysis.metrics.imports.length > 0) {
    lines.push(
      `## 📦 Module Dependencies & Imports (${analysis.metrics.imports.length})`,
      ``,
      `| Module / Package | Type | Line | Risk / Advisory |`,
      `| :--- | :--- | :--- | :--- |`
    );

    analysis.metrics.imports.forEach((imp) => {
      lines.push(
        `| \`${imp.module}\` | ${imp.isExternal ? 'External NPM' : 'Internal'} | ${imp.line} | ${imp.riskNote || 'Standard'} |`
      );
    });
    lines.push(``);
  }

  // 7. Pulse Map Topology Block
  if (blocks.showPulseMap && options.includePulseMap && analysis.pulseMap.nodes.length > 0) {
    lines.push(
      `## 🌐 Pulse Map Topology Nodes`,
      ``,
      `Topology includes **${analysis.pulseMap.nodes.length} nodes** and **${analysis.pulseMap.links.length} structural links**.`,
      ``,
      `| Node | Type | Line | Complexity | Group |`,
      `| :--- | :--- | :--- | :--- | :--- |`
    );

    analysis.pulseMap.nodes.slice(0, 15).forEach((node) => {
      lines.push(
        `| \`${node.label}\` | ${node.type} | ${node.line || '—'} | ${node.metrics?.complexity ?? '—'} | ${node.group || '—'} |`
      );
    });

    if (analysis.pulseMap.nodes.length > 15) {
      lines.push(`*...and ${analysis.pulseMap.nodes.length - 15} additional topology nodes.*`);
    }
    lines.push(``);
  }

  // 8. AI Architectural Guidance Block
  if (blocks.showAiGuidance && options.includeAiSummary && aiSummaryText) {
    lines.push(
      `## 💡 Pulse AI Architectural Insights & Guidance`,
      ``,
      aiSummaryText.trim(),
      ``
    );
  }

  // 9. Footer & Disclaimer Block
  if (blocks.showFooter) {
    lines.push(
      `---`,
      `*${template.footerDisclaimer || 'Confidential & Proprietary — Generated by DevPulse Observability Platform'}*`
    );
  }

  return lines.join('\n');
}

/**
 * Export Analysis & Pulse Map data as a Markdown file (.md)
 */
export function exportAnalysisAsMarkdown(
  analysis: AnalysisResult,
  code: string,
  fileName: string,
  options: ExportOptions = defaultOptions,
  aiSummaryText?: string
): void {
  const mdContent = generateMarkdownReport(analysis, code, fileName, options, aiSummaryText);
  const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  const safeName = (fileName || 'code_intelligence').replace(/\.[^/.]+$/, '');
  link.href = url;
  link.download = `devpulse-report-${safeName}-${new Date().toISOString().slice(0, 10)}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Builds a styled jsPDF Document instance from AnalysisResult and Template configuration
 */
export function buildPDFDoc(
  analysis: AnalysisResult,
  code: string,
  fileName: string,
  options: ExportOptions = defaultOptions,
  aiSummaryText?: string
): jsPDF {
  const template = options.template || DEFAULT_TEMPLATE_CONFIG;
  const blocks = template.blocks;
  const colors = getAccentColorRGB(template.accentColor);

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let currentY = 18;

  const addHeader = (pageNum: number) => {
    // Top Brand Strip in Accent Color
    doc.setFillColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.rect(margin, 10, contentWidth, 2, 'F');

    // Organization & Brand Text
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.text((template.organizationName || 'DEVPULSE INTELLIGENCE').toUpperCase(), margin, 8);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(120, 120, 120);
    const dateStr = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
    doc.text(`Generated: ${dateStr}`, pageWidth - margin - 45, 8);

    // Footer
    if (blocks.showFooter) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(140, 140, 140);
      const footerMsg = template.footerDisclaimer || 'DevPulse — "See the Code. Find the Pulse."';
      doc.text(footerMsg.slice(0, 75), margin, pageHeight - 8);
      doc.text(`Page ${pageNum}`, pageWidth - margin - 15, pageHeight - 8);
    }
  };

  let pageIndex = 1;
  addHeader(pageIndex);

  const checkPageBreak = (neededHeight: number) => {
    if (currentY + neededHeight > pageHeight - 20) {
      doc.addPage();
      pageIndex++;
      addHeader(pageIndex);
      currentY = 22;
    }
  };

  // 1. Title Block
  if (blocks.showHeader) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(17);
    doc.setTextColor(18, 30, 28);
    doc.text(template.reportTitle || 'Code Intelligence & Pulse Map Audit', margin, currentY);
    currentY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(80, 95, 90);
    doc.text(
      `Target: ${fileName || 'Source Code'}  |  Language: ${analysis.languageName}  |  Lines: ${analysis.metrics.loc} LOC`,
      margin,
      currentY
    );
    currentY += 5;

    // Author & Confidentiality Badge Row
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.text(`Auditor: ${template.authorName || 'DevPulse System'}   •   [ ${template.confidentialityNote || 'Confidential'} ]`, margin, currentY);
    currentY += 8;
  }

  // Custom Executive / Scope Notes Box
  if (blocks.showCustomNotes && template.customSummaryNote && template.customSummaryNote.trim().length > 0) {
    checkPageBreak(25);
    doc.setFillColor(colors.subtleBg[0], colors.subtleBg[1], colors.subtleBg[2]);
    doc.setDrawColor(colors.border[0], colors.border[1], colors.border[2]);
    const noteLines = doc.splitTextToSize(template.customSummaryNote.trim(), contentWidth - 10);
    const boxHeight = Math.max(14, noteLines.length * 4.2 + 6);
    doc.roundedRect(margin, currentY, contentWidth, boxHeight, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(colors.text[0], colors.text[1], colors.text[2]);
    doc.text('EXECUTIVE AUDIT NOTES:', margin + 4, currentY + 5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(40, 50, 50);
    doc.text(noteLines, margin + 4, currentY + 9.5);
    currentY += boxHeight + 6;
  }

  // 2. Executive Scorecard Box
  if (blocks.showExecutiveSummary) {
    checkPageBreak(36);
    const healthScore = analysis.metrics.healthScore;
    const healthLevel = analysis.summary.healthLevel;
    const maintainability = analysis.metrics.maintainabilityScore;
    const cyclomatic = analysis.metrics.cyclomaticComplexity;
    const cognitive = analysis.metrics.cognitiveComplexity;

    // Background Box
    doc.setFillColor(245, 248, 247);
    doc.setDrawColor(colors.border[0], colors.border[1], colors.border[2]);
    doc.roundedRect(margin, currentY, contentWidth, 32, 3, 3, 'FD');

    // Health Score Big Number
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    if (healthScore >= 85) doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    else if (healthScore >= 70) doc.setTextColor(217, 119, 6);
    else doc.setTextColor(225, 29, 72);
    doc.text(`${healthScore}`, margin + 8, currentY + 16);

    doc.setFontSize(10);
    doc.setTextColor(100, 110, 110);
    doc.text('/ 100', margin + 30, currentY + 16);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.text(`HEALTH: ${healthLevel.toUpperCase()}`, margin + 8, currentY + 24);

    // Key Metric Columns
    const colX1 = margin + 55;
    const colX2 = margin + 105;
    const colX3 = margin + 145;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 110, 110);
    doc.text('Maintainability Index', colX1, currentY + 10);
    doc.text('Cyclomatic Complexity', colX2, currentY + 10);
    doc.text('Cognitive Complexity', colX3, currentY + 10);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(20, 30, 30);
    doc.text(`${maintainability}/100`, colX1, currentY + 20);
    doc.text(`${cyclomatic}`, colX2, currentY + 20);
    doc.text(`${cognitive}`, colX3, currentY + 20);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(`${analysis.smells.length} total code smells detected`, colX1, currentY + 27);
    doc.text(`Max Nesting: ${analysis.metrics.maxNestingDepth}`, colX2, currentY + 27);
    doc.text(`Avg Func Length: ${analysis.metrics.averageFunctionLength} lines`, colX3, currentY + 27);

    currentY += 38;
  }

  // 3. Metrics Matrix Table
  if (blocks.showMetrics && options.includeMetrics) {
    checkPageBreak(35);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.text('Codebase Dimensions & Architecture Metrics', margin, currentY);
    currentY += 6;

    const metricsList = [
      ['Physical Lines (LOC)', `${analysis.metrics.loc}`],
      ['Source Lines (SLOC)', `${analysis.metrics.sloc}`],
      ['Comment Ratio', `${analysis.metrics.commentRatio}%`],
      ['Functions & Methods', `${analysis.metrics.functionCount}`],
      ['Classes Declared', `${analysis.metrics.classCount}`],
      ['Dependencies / Imports', `${analysis.metrics.dependenciesCount} (${analysis.metrics.externalDependenciesCount} external)`],
      ['Structural Health Score', `${analysis.metrics.scoreBreakdown.structure}/100`],
      ['Maintainability Score', `${analysis.metrics.scoreBreakdown.maintainability}/100`],
    ];

    const boxW = (contentWidth - 6) / 2;
    metricsList.forEach(([label, val], idx) => {
      const isRightCol = idx % 2 === 1;
      const x = isRightCol ? margin + boxW + 6 : margin;
      const rowY = currentY + Math.floor(idx / 2) * 9;

      doc.setFillColor(250, 252, 251);
      doc.setDrawColor(225, 235, 232);
      doc.roundedRect(x, rowY, boxW, 7.5, 1.5, 1.5, 'FD');

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(80, 95, 90);
      doc.text(label, x + 3, rowY + 5);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(20, 35, 30);
      doc.text(val, x + boxW - 4, rowY + 5, { align: 'right' });
    });

    currentY += Math.ceil(metricsList.length / 2) * 9 + 6;
  }

  // 4. Code Smells & Detected Vulnerabilities
  if (blocks.showSmells && options.includeSmells && analysis.smells.length > 0) {
    checkPageBreak(30);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.text(`Detected Code Smells & Security Findings (${analysis.smells.length})`, margin, currentY);
    currentY += 6;

    analysis.smells.slice(0, 8).forEach((smell: CodeSmell, sIdx: number) => {
      checkPageBreak(24);

      // Smell item card
      doc.setFillColor(252, 253, 252);
      doc.setDrawColor(220, 230, 228);
      doc.roundedRect(margin, currentY, contentWidth, 20, 2, 2, 'FD');

      // Severity Tag
      let sevBg = [204, 251, 241];
      let sevText = [13, 148, 136];
      if (smell.severity === 'critical') {
        sevBg = [255, 228, 230];
        sevText = [225, 29, 72];
      } else if (smell.severity === 'warning') {
        sevBg = [254, 243, 199];
        sevText = [217, 119, 6];
      }

      doc.setFillColor(sevBg[0], sevBg[1], sevBg[2]);
      doc.roundedRect(margin + 3, currentY + 3, 18, 4.5, 1, 1, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.5);
      doc.setTextColor(sevText[0], sevText[1], sevText[2]);
      doc.text(smell.severity.toUpperCase(), margin + 12, currentY + 6.2, { align: 'center' });

      // Title & Line
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(20, 35, 30);
      doc.text(`${sIdx + 1}. ${smell.title}`, margin + 24, currentY + 6.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(120, 130, 130);
      doc.text(`Line ${smell.line}`, pageWidth - margin - 5, currentY + 6.5, { align: 'right' });

      // Problem description
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(60, 75, 70);
      const problemLines = doc.splitTextToSize(`Problem: ${smell.problem}`, contentWidth - 8);
      doc.text(problemLines.slice(0, 2), margin + 4, currentY + 11.5);

      // Recommendation
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7.5);
      doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
      const fixLines = doc.splitTextToSize(`Fix: ${smell.recommendation}`, contentWidth - 8);
      doc.text(fixLines.slice(0, 1), margin + 4, currentY + 17.5);

      currentY += 23;
    });

    if (analysis.smells.length > 8) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text(`... and ${analysis.smells.length - 8} more findings detailed in JSON export.`, margin + 4, currentY);
      currentY += 6;
    }
  }

  // 5. Code Pulse Map Topology Overview
  if (blocks.showPulseMap && options.includePulseMap) {
    checkPageBreak(35);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.text('Code Pulse Map Structural Topology', margin, currentY);
    currentY += 6;

    const nodes = analysis.pulseMap.nodes;
    const links = analysis.pulseMap.links;

    doc.setFillColor(245, 248, 247);
    doc.setDrawColor(colors.border[0], colors.border[1], colors.border[2]);
    doc.roundedRect(margin, currentY, contentWidth, 24, 2.5, 2.5, 'FD');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(40, 55, 50);
    doc.text(
      `Topology Graph Nodes: ${nodes.length} items   |   Structural Links: ${links.length} relationships`,
      margin + 6,
      currentY + 7
    );

    const fileNodes = nodes.filter((n) => n.type === 'file').length;
    const classNodes = nodes.filter((n) => n.type === 'class').length;
    const funcNodes = nodes.filter((n) => n.type === 'function').length;
    const impNodes = nodes.filter((n) => n.type === 'import').length;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.text(
      `Files: ${fileNodes}   ·   Classes: ${classNodes}   ·   Functions/Methods: ${funcNodes}   ·   Imports: ${impNodes}`,
      margin + 6,
      currentY + 14
    );

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 115, 110);
    doc.text(
      'Visual topology maps caller-callee bindings, import dependencies, and complexity hotspots.',
      margin + 6,
      currentY + 20
    );

    currentY += 28;
  }

  // 6. AI Summary Section
  if (blocks.showAiGuidance && options.includeAiSummary && aiSummaryText) {
    checkPageBreak(35);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.text('Pulse AI Architectural Recommendations', margin, currentY);
    currentY += 6;

    doc.setFillColor(248, 250, 249);
    doc.setDrawColor(210, 225, 220);
    const summaryLines = doc.splitTextToSize(aiSummaryText.slice(0, 1200), contentWidth - 10);
    const boxHeight = Math.min(60, summaryLines.length * 4.2 + 8);
    doc.roundedRect(margin, currentY, contentWidth, boxHeight, 2, 2, 'FD');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(40, 50, 50);
    doc.text(summaryLines.slice(0, 13), margin + 5, currentY + 6);
    currentY += boxHeight + 6;
  }

  return doc;
}

/**
 * Returns PDF document as a Blob for direct cloud / drive uploading
 */
export function generatePDFBlob(
  analysis: AnalysisResult,
  code: string,
  fileName: string,
  options: ExportOptions = defaultOptions,
  aiSummaryText?: string
): Blob {
  const doc = buildPDFDoc(analysis, code, fileName, options, aiSummaryText);
  return doc.output('blob');
}

/**
 * Export Analysis & Pulse Map data as a styled PDF report
 */
export function exportAnalysisAsPDF(
  analysis: AnalysisResult,
  code: string,
  fileName: string,
  options: ExportOptions = defaultOptions,
  aiSummaryText?: string
): void {
  const doc = buildPDFDoc(analysis, code, fileName, options, aiSummaryText);
  const safeName = (fileName || 'code_intelligence').replace(/\.[^/.]+$/, '');
  doc.save(`devpulse-report-${safeName}-${new Date().toISOString().slice(0, 10)}.pdf`);
}
